name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install-submodules
      run: git submodule update --init --recursive
    - name: install-py-requirements
      run: pip3 install -r requirements.txt
    - name: make
      run: make
    - name: run-tests
      run: python3 tests/run_tests.py --no-compile --fail-fast